/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from '@angular/forms';
import { minValueValidator, maxValueValidator, enumValidator } from './validators';
import { BaseModel } from './base-model';

import { type } from './enums';
import { gender } from './enums';
import { Address } from './address.model';
import { Veterinarian } from './veterinarian.model';
import { Tag } from './tag.model';
import { NullableOrEmpty } from './nullable-or-empty.model';

export interface IPet {
    name: string;
    age?: number;
    dob?: Date;
    type: type;
    gender?: gender;
    address?: Address;
    vet?: Veterinarian;
    tags?: Array<Tag>;
    isFavorate?: boolean;
    testDate?: NullableOrEmpty<Date>;
    primitiveArray?: Array<string>;
}

export class Pet extends BaseModel implements IPet {
    name: string;
    age: number;
    dob: Date;
    type: type;
    gender: gender;
    address: Address;
    vet: Veterinarian;
    tags: Array<Tag>;
    isFavorate: boolean;
    testDate: NullableOrEmpty<Date>;
    primitiveArray: Array<string>;

    /** 
     * constructor
     * @param values Can be used to set a webapi response to this newly constructed model   
    */
    constructor(values?: any) {
        super();
        this.address = new Address();
        this.vet = new Veterinarian();
        this.tags = new Array<Tag>();
        this.testDate = new NullableOrEmpty<Date>();
        this.primitiveArray = new Array<string>();
        if (values) {
            this.setValues(values);
        }
    }

    /** 
     * set the values.
     * @param values Can be used to set a webapi response to this newly constructed model
    */
    setValues(values: any): void {
        if (values) {
            this.name = values.name;
            this.age = values.age;
            this.dob = values.dob;
            this.type = values.type;
            this.gender = values.gender;
            this.address.setValues(values.address);
            this.vet.setValues(values.vet);
            this.fillModelArray<Tag>(this, 'tags', values.tags, Tag);
            this.isFavorate = values.isFavorate;
            this.testDate.setValues(values.testDate);
            this.fillModelArray<string>(this, 'primitiveArray', values.primitiveArray);
        }
    }

    protected getFormGroup(): FormGroup {
        if (!this._formGroup) {
            this._formGroup = new FormGroup({
                name: new FormControl(this.name, [Validators.required, Validators.minLength(4), Validators.pattern('^[a-zA-Z0-9- ]+$'), ]),
                age: new FormControl(this.age),
                dob: new FormControl(this.dob),
                type: new FormControl(this.type, [Validators.required, enumValidator(type), ]),
                gender: new FormControl(this.gender, [enumValidator(gender), ]),
                address: this.address.$formGroup,
                vet: this.vet.$formGroup,
                tags: new FormArray([]),
                isFavorate: new FormControl(this.isFavorate),
                testDate: this.testDate.$formGroup,
                primitiveArray: new FormArray([]),
            });
            // generate FormArray control elements
            this.fillFormArray<Tag>('tags', this.tags, Tag);
            // generate FormArray control elements
            this.fillFormArray<string>('primitiveArray', this.primitiveArray);
        }
        return this._formGroup;
    }

    setFormGroupValues() {
        if (this._formGroup) {
            this._formGroup.controls['name'].setValue(this.name);
            this._formGroup.controls['age'].setValue(this.age);
            this._formGroup.controls['dob'].setValue(this.dob);
            this._formGroup.controls['type'].setValue(this.type);
            this._formGroup.controls['gender'].setValue(this.gender);
            this.address.setFormGroupValues();
            this.vet.setFormGroupValues();
            this.fillModelArray<Tag>(this, 'tags', this.tags, Tag);
            this._formGroup.controls['isFavorate'].setValue(this.isFavorate);
            this.testDate.setFormGroupValues();
            this.fillModelArray<string>(this, 'primitiveArray', this.primitiveArray);
        }
    }
}
